version: '2'

services:
  hadoop-master:
    container_name: hadoop-master
    image: kgiann78/ms-thesis-hadoop-spark:1.1
    networks:
      - hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "10000:10000"
      - "4040:4040"
      - "7070:7070"
      - "7077:7077"
      - "8033:8033"
      - "8032:8032"
      - "8031:8031"
      - "8030:8030"
    hostname: hadoop-master
    restart: always

  hadoop-slave:
    container_name: hadoop-slave
    image: kgiann78/ms-thesis-hadoop-spark:1.1
    networks:
      - hadoop
    hostname: hadoop-slave
    depends_on:
      - hadoop-master
    restart: always

networks:
  hadoop:
    driver: bridge
